<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="tuba-PC" name="testCases.TC1_2NavigateToLogInPage" tests="6" failures="0" timestamp="12 Jul 2018 00:56:16 GMT" time="26.950" errors="1">
  <testcase name="verifyPageLabel" time="1.301" classname="testCases.TC1_2NavigateToLogInPage"/>
  <testcase name="verifyPageLabel" time="0.000" classname="testCases.TC1_2NavigateToLogInPage">
    <skipped/>
  </testcase> <!-- verifyPageLabel -->
  <testcase name="verifyInvalidLogInToApplicationNegetive" time="1.388" classname="testCases.TC1_2NavigateToLogInPage"/>
  <testcase name="verifyInvalidLogInToApplicationNegetive" time="0.000" classname="testCases.TC1_2NavigateToLogInPage">
    <skipped/>
  </testcase> <!-- verifyInvalidLogInToApplicationNegetive -->
  <testcase name="verifyvalidLogInToApplicationPositive" time="24.261" classname="testCases.TC1_2NavigateToLogInPage">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testCases.TC1_2NavigateToLogInPage.verifyvalidLogInToApplicationPositive(TC1_2NavigateToLogInPage.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyvalidLogInToApplicationPositive -->
  <testcase name="verifyvalidLogInToApplicationPositive" time="0.000" classname="testCases.TC1_2NavigateToLogInPage">
    <skipped/>
  </testcase> <!-- verifyvalidLogInToApplicationPositive -->
</testsuite> <!-- testCases.TC1_2NavigateToLogInPage -->
